Add r and rstudio images
cityofcapetown/docker_datascience pull request #34
Opened 2024-09-17 11:36 UTC by riazarbi

This PR does the following:

1. Remove rsession image (broken anyway)
2. Add an r and rstudio image.
3. Update the README.md

The r image has a working R installation. It also checks what the Ubuntu system requirements for the top 100 downloaded packages on CRAN over the last month are, and installs those. It does not install the actual R packages. This keeps the image slim, but makes per-project package installs likely to succeed.

The Rstudio image has Jupyter, Rstudio and VScode installed, and is configured to launch Jupyter in the same fashion as jupyter-ide. 

The python_minimal image is 2.92GB. The r image is 4.44GB, and the Rstudio image is 6.82GB. This compares favourably with the Jupyter stack - jupyter-ide is 8.22GB.

This PR has not modified any jenkins configs, so these images won't build automatically, you need to build them manually until you incorporate them into CI.

2024-09-17 12:56 UTC, Gordonei requested changes
Your commit(ment) drives the City forward!

2024-09-17 12:56 UTC, Gordonei commented on README.md
> +            |       └── jupyter-k8s
`jupyter-ide` is at the same level as `python`

```suggestion
            |   ├── jupyter-ide
            |   └── python
            |       └── jupyter-k8s
```

2024-09-17 12:56 UTC, Gordonei commented on README.md
> +```
thanks, a useful addition to the docs

2024-09-17 12:56 UTC, Gordonei commented on base/drivers/python_minimal/r/rstudio/Dockerfile
> + && pip3 install jupyter-vscode-proxy
let me check with the team, but don't know if anyone is actively doing R work outside of VS Code

How much space it adds to the image?

2024-09-17 13:18 UTC, riazarbi commented on base/drivers/python_minimal/r/rstudio/Dockerfile
> + && pip3 install jupyter-vscode-proxy
With VSCode - 6.82Gb
Without VSCode - 5.82Gb

2024-09-17 13:38 UTC, riazarbi commented
There will be some setup required for the R users when they spawn this image for the first time. In particular - 

1. Set up proxy so that the IDE can hit CRAN and optionally apt to install packages
2. `quarto install tinytex` will install tinytex to $HOME. This hasn't been done because $HOME is mounted to it would get overwritten is installed prior.

There is pretty good integration for `renv` in Rstudio.

2024-09-18 06:55 UTC, Gordonei commented on base/drivers/python_minimal/r/rstudio/Dockerfile
> + && pip3 install jupyter-vscode-proxy
Thinking about it more, what I'll rather do is move `jupyter-ide` below `r_minimal`, and add the R VS Code extension there, so remove it from here for now, please.

The idea was always that `jupyter-ide` would be for preparing stuff for production, hence is usually the time when people want to use IDEs

2024-09-18 08:00 UTC, riazarbi commented on base/drivers/python_minimal/r/rstudio/Dockerfile
> + && pip3 install jupyter-vscode-proxy
Done

2024-09-18 08:00 UTC, riazarbi commented
Ok, I think you are good to go.

2024-09-19 20:03 UTC, Gordonei commented
LGTM

2024-09-19 20:04 UTC, merged